[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://web-production-1c18.up.railway.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://web-production-1c18.up.railway.app"
